apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hw2service-chart.fullname" . }}
  labels:
    {{- include "hw2service-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}   
  selector:
    matchLabels:
      {{- include "hw2service-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hw2service-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /hc
              port: 8000
          readinessProbe:
            httpGet:
              path: /hc
              port: 8000
          env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DATABASE_URI
          volumeMounts:
          - name: configmap-volume
            mountPath: "/app/appsettings.json"
            subPath: appsettings.json
            readOnly: true
      volumes:
      - name: configmap-volume
        configMap:
          name: api-configmap