{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hw2service-chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "hw2service-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
        {{- range .paths }}
      - pathType: Prefix
        path: {{ . }}
        backend:
          service:
            name: {{ $fullName }}
            port: 
               number: {{ $svcPort }}
  ingressClassName: nginx
          {{- end }}
    {{- end }}
  {{- end }}